### ISSUE TITLE
Add missing example as a service

### ISSUE THREAD

**Issue by emulienfou** [kevintweber/KtwDatabaseMenuBundle#18]
Hi, I think it would be great to add some documentation in relation to add menu as a service like explained in the official KnpMenu documentation: [Creating Menus as Services](http://symfony.com/doc/master/bundles/KnpMenuBundle/menu_service.html).

Here is an example of my configuration:
```yaml
app.menu_builder:
        class: AppBundle\Menu\MenuBuilder
        arguments: ['@ktw_database_menu.factory', '@doctrine.orm.entity_manager']

    app.main_menu:
        class: Knp\Menu\MenuItem # the service definition requires setting the class
        factory: ["@app.menu_builder", createMainMenu]
        tags:
            - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu
```

If it can help people to do the same and not spent hours to find the right configuration!
